boxes/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'boxes'

urlpatterns = [
    path('', views.index, name='home'),
    path('login', views.CustomLoginView.as_view(), name='login'),
    path('logout', views.logout_view, name='logout'),
    path('profile', views.profile_page, name='user_profile'),
    path('random_page', views.random_page, name='losuj')
]

los_szczescia/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from los_szczescia import settings

urlpatterns = [
    path('', include('boxes.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

boxes/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Family(models.Model):
    family_name = models.CharField(max_length=200)


class Person(AbstractUser):
    username = models.CharField(max_length=50, unique=True, verbose_name="Pseudonim")
    first_name = models.CharField(max_length=50, verbose_name="Imię")
    second_name = models.CharField(max_length=20, verbose_name="Nazwisko")
    password = models.CharField(max_length=2000, verbose_name="Hasło")
    family = models.ForeignKey(Family, on_delete=models.CASCADE, blank=True, null=True)
    chosen_person = models.ForeignKey('Person', on_delete=models.CASCADE, blank=True, null=True)
    is_chosen = models.BooleanField(default=False)
    is_man = models.BooleanField(default=False)

    def full_name(self):
        return self.first_name + " " + self.second_name

    def __str__(self):
        return self.full_name()


class Changer(models.Model):
    possible = models.BooleanField(default=False)

boxes/forms.py
from django.contrib.auth.forms import AuthenticationForm

from boxes.models import Person


class UserLoginForm(AuthenticationForm):
    error_messages = {
        'invalid_login': (
            "Proszę podać poprawne Imię i Hasło. Wielkość liter ma znaczenie!"
        ),
        'inactive': ("Konto nie istnieje."),
    }

    class Meta:
        model = Person

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Pseudonim'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Hasło', 'name': 'Hasło'})


from django import forms


class CleanSelectionForm(forms.ModelForm):
    """ form to choose professor to show their schedule"""
    user_to_clean = forms.ModelChoiceField(queryset=Person.objects.all(), to_field_name='id')

    class Meta:
        model = Person
        fields: list = []

boxes/views.py
import random

from django.core.exceptions import ValidationError
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.views import View

from boxes.forms import UserLoginForm, CleanSelectionForm
from boxes.models import Person, Changer


def index(request):
    return render(request, 'index.html')


@login_required
def profile_page(request):
    current_user = Person.objects.get(username=request.user.username)
    context = {
        'person': current_user
    }
    return render(request, 'profile.html', context)


@login_required
def random_page(request):
    chosen_person = None
    if request.method == "POST":
        if request.POST.get('losuj_button'):
            current_user = Person.objects.get(username=request.user.username)
            if current_user.chosen_person is None:
                possible_users = Person.objects.all() \
                    .exclude(family=current_user.family) \
                    .filter(is_chosen=False) \
                    .exclude(is_superuser=True)
                if possible_users:
                    random_person = random.choice(possible_users)
                    random_person.is_chosen = True
                    random_person.save()
                    current_user.chosen_person = random_person
                    current_user.save()
                    messages.success(request, 'Poprawnie wylosowano! Sprawdź, kogo!')
                else:
                    messages.error(request,
                                   'Poważny konflikt interesów! Brak wolnych losów! '
                                   'Skontaktuj się z pomocą techniczną!')
            else:
                messages.error(request, 'Już wylosowano! Jeden prezent do kupienia wystarczy!')
        if request.POST.get('check'):
            current_user = Person.objects.get(username=request.user.username)
            if current_user.chosen_person is None:
                messages.error(request,
                               'Jeszcze nie ma wylosowanej osoby! Sprawdź później.')
            else:
                chosen_person = current_user.chosen_person

        if request.POST.get('ha'):
            current_user = Person.objects.get(username=request.user.username)

            while True:
                people = Person.objects.all().exclude(is_superuser=True).filter(chosen_person=None)
                if not people:
                    return render(request, 'losuj.html')
                current_per = random.choice(people)
                if current_per.chosen_person is None:
                    possible_users = Person.objects.all() \
                        .exclude(family=current_per.family) \
                        .filter(is_chosen=False) \
                        .exclude(is_superuser=True)
                    if possible_users:
                        random_person = random.choice(possible_users)
                        random_person.is_chosen = True
                        random_person.save()
                        current_per.chosen_person = random_person
                        current_per.save()
                        # print(current_per)
                    else:
                        messages.error(request,
                                       'Poważny konflikt interesów! Brak wolnych losów! '
                                       'Skontaktuj się z pomocą techniczną! %s' % current_per.username)
                        return render(request, 'losuj.html')
                else:
                    messages.error(request,
                                   'Już wylosowano dla %s' % current_per.username)

        if request.POST.get('clean'):
            current_user = Person.objects.get(username=request.user.username)
            people = Person.objects.all().exclude(is_superuser=True)
            people.update(is_chosen=False)
            people.update(chosen_person=None)

        if request.POST.get('simple_clean'):
            form = CleanSelectionForm(request.POST)
            if form.is_valid():
                user_to_clean = form.cleaned_data['user_to_clean'].username
                print(user_to_clean)
                persona = Person.objects.get(username=user_to_clean)
                if persona.chosen_person is None:
                    messages.error(request,
                                   'Nie wylosowano dla %s' % persona.username)
                else:
                    this_username = persona.chosen_person.username
                    persona.chosen_person = None
                    persona.save()
                    user_selected_user = Person.objects.get(username=this_username)
                    user_selected_user.is_chosen = False
                    user_selected_user.save()
                    messages.error(request,
                                   'Wyczyszczono dla %s' % persona.username)
                render(request, 'losuj.html', {'goal': chosen_person, 'form': form})

        if request.POST.get('supercheck'):
            print("supercheck")
            current_user = Person.objects.get(username=request.user.username)
            people = Person.objects.all().exclude(is_superuser=True)
            chosen_people = []
            for person in people:
                if person.chosen_person is not None:
                    chosen_people.append(person.chosen_person)
                    chosen_person_family = person.chosen_person.family.family_name
                    person_family = person.family.family_name

                    if chosen_person_family == person_family:
                        messages.error(request,
                                       'Błąd w losowaniu :( '
                                       '%s == %s' % (chosen_person_family, person_family))
                    else:
                        messages.success(request, "Poprawne dopasowanie!")
                else:
                    messages.info(request, "Nie wylosowano!")
            for person in chosen_people:
                messages.info(request, "%s wylosowano" % person.username)

        if request.POST.get("superchange"):
            current_changer = Changer.objects.all()[0]
            current_changer.update(possible=(not current_changer))
            print(current_changer.possible)
    return render(request, 'losuj.html', {'goal': chosen_person, 'form': CleanSelectionForm()})


@login_required
def logout_view(request):
    logout(request)
    return redirect('boxes:login')


class CustomLoginView(View):
    def get(self, request):
        return render(request, 'registration/login.html', {'form': UserLoginForm})

    def post(self, request):
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            try:
                form.clean()
            except ValidationError:
                return render(request, 'registration/login.html', {'form': form, 'invalid_creds': True})
            login(request, form.get_user())
            return redirect('boxes:user_profile')

        return render(request, 'registration/login.html', {'form': form})

boxes/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Los szczęścia</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    {% block static %}{% endblock static %}
    {% block script %}{% endblock script %}

    <style>
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: GhostWhite;
            color: grey;
            text-align: center;
            font-size: 11px;
            padding-bottom: 3px;
            padding-top: 3px;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-expand-sm bg-light">

    <a class="navbar-brand" href="{% url 'boxes:home' %}">LosSzczęścia</a>

    <div class="container-fluid">
        {% block navbar %}{% endblock navbar %}
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'boxes:logout' %}">
                    <i class="material-icons" style="font-size: 12px">lock</i> Wyloguj</a>
                </li>
            {% else %}
                <li><a class="nav-link" href="{% url 'boxes:login' %}">
                    <i class="material-icons" style="font-size: 12px">lock_open</i> Zaloguj</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

{% block content %}

{% endblock content %}

<div class="footer" style="margin-bottom:0">
    &copy; Copyright 2020,
    <a href="{% url 'boxes:home' %}">CUD_TEAM</a>. All rights reserved.
</div>
</body>
</html>

boxes/templates/index.html
{% extends 'base.html' %}


{% block navbar %}
    <ul class="nav navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'boxes:home' %}">Strona główna</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'boxes:user_profile' %}"> Mój profil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'boxes:losuj' %}"> Losuj</a>
            </li>
        {% endif %}
    </ul>
{% endblock navbar %}


{% block content %}
    <div class="jumbotron text-center">
        <h2>Los szczęścia!</h2>

        <div>
            <cite>
                Ludzie, ludzie zwariowałem! Pieniądze rozdaję! <br>
                Każdy szczęściu dopomoże, każdy dzisiaj wygrać może. Raz, dwa, trzy...
            </cite>
        </div>
        <p></p>
        <div>
            Jeśli bierzesz udział w losowaniu, <a class="nav-link" href="{% url 'boxes:login' %}">zaloguj się.</a>
            Dalesze instrukcje zobaczysz w panelu użytkownika.
        </div>
        <p></p>
        <div>
            {% load static %}
            <img src="{% static 'obraz.png' %}"
                 style="width: 50%"
                 class="mx-auto rounded" alt="Wesołych Świąt!"/>
        </div>
    </div>

{% endblock content %}

boxes/templates/losuj.html
{% extends 'base.html' %}


{% block navbar %}
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'boxes:home' %}">Strona główna </a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'boxes:user_profile' %}"> Mój profil</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'boxes:losuj' %}"> Losuj</a>
            </li>
        {% endif %}
    </ul>
{% endblock navbar %}


{% block content %}

    <div class="container-fluid">
        <div class="jumbotron">
            {% if user.is_authenticated %}

                <div class="container-fluid" style="text-align: center;">
                    Na tej stronie znajdują się najważniejsze przyciski w aplikacji.<br>
                    Klikając perwszy przycisk, można wylosować dla siebie jedną osobę (przycisk "Losuj").<br>
                    Natomiast drugi przycisk ("Sprawdź") - pozwala na sprawdzenie, kogo się wylosowało.
                </div>

                <p></p>

                <div class="row">
                    <div class="col card bg-light text-dark align-middle"
                         style="padding-top: 25px; padding-bottom: 25px;">
                        <div> {{ user.username }}, tutaj możesz uruchomić maszynę losującą oraz sprawdzić,
                            kto w wyniku losowania został wskazany przez liczby pseudolosowe.
                        </div>
                        <p></p>

                        <div class="container">
                            <form method="POST">
                                {% csrf_token %}
                                <button type="submit" name="losuj_button" value="clicked"
                                        class="btn btn-primary btn-block btn-lg">
                                    Losuj
                                </button>
                            </form>
                            <p></p>
                            <form method="POST">
                                {% csrf_token %}
                                <button type="submit" name="check" value="clicked"
                                        class="btn btn-primary btn-block btn-lg">
                                    Sprawdź
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="col">

                        {% if goal is not None %}
                            <div class="jumbotron media border">

                                <div class="media-body">

                                    <div class="card" style="width:400px">
                                        <div class="card-header">
                                            Wylosowany szczęśliwiec
                                        </div>

                                        <div class="card-body">
                                            <div class="card-text">
                                                <ul>
                                                    <p> Nazwisko: {{ goal.second_name }} </p>
                                                    <p> Imię: {{ goal.first_name }} </p>
                                                </ul>
                                            </div>
                                        </div>

                                    </div>

                                </div>

                                {% if goal.is_man %}
                                    {% load static %}
                                    <img src="{% static 'avatar_m.png' %}" alt="John Doe"
                                         class="ml-3 rounded-circle card-img-bottom"
                                         style="width: 200px;">
                                {% else %}
                                    {% load static %}
                                    <img src="{% static 'avatar_f.png' %}" alt="John Doe"
                                         class="ml-3 mt-3 rounded-circle card-img-bottom"
                                         style="width: 200px;">
                                {% endif %}
                            </div>
                        {% endif %}

                        <div class="container-fluid align-middle">
                            {% if error_message %}
                                <div class="alert alert-success">

                                    <p><strong>{{ error_message }}</strong></p>
                                </div>

                            {% endif %}

                            {% if messages %}
                                <div class="alert alert-success">
                                    {% for message in messages %}
                                        <p><strong>{{ message }}</strong></p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>

                        <p></p>

                    </div>

                    {% if user.is_superuser %}
                        <div class="col card bg-light text-dark align-middle"
                             style="padding-top: 25px; padding-bottom: 25px;">

                            <h3 style="text-align: center;">Panel administratora</h3>
                            <div class="container">
                                <form method="POST">
                                    {% csrf_token %}
                                    <button type="submit" name="ha" value="clicked"
                                            class="btn btn-primary btn-block btn-lg">
                                        Wylosuj wszystkim!
                                    </button>
                                </form>
                            </div>
                            <p></p>
                            <div class="container">
                                <form method="POST">
                                    {% csrf_token %}
                                    <button type="submit" name="clean" value="clicked"
                                            class="btn btn-primary btn-block btn-lg">
                                        Wyczyść!
                                    </button>
                                </form>
                            </div>
                            <p></p>
                            <div class="container">
                                <form method="POST">
                                    {% csrf_token %}
                                    <button type="submit" name="supercheck" value="clicked"
                                            class="btn btn-primary btn-block btn-lg">
                                        Sprawdzam!
                                    </button>
                                </form>
                            </div>
                            <p></p>
                            <div class="container">
                                <form method="POST">
                                    {% csrf_token %}
                                    <button type="submit" name="superchange" value="clicked"
                                            class="btn btn-primary btn-block btn-lg">
                                        Wymiana! Nie działa...
                                    </button>
                                </form>
                            </div>
                            <p></p>
                            <div class="container">
                                <form method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ next }}">
                                    {{ form.as_p }}
                                    <button type="submit" name="simple_clean" value="clicked"
                                            class="btn btn-primary btn-block btn-lg">
                                        Małe czyszczenie!
                                    </button>
                                </form>
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% endif %}

        </div>
    </div>

{% endblock content %}

boxes/templates/profile.html
{% extends 'base.html' %}


{% block navbar %}
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'boxes:home' %}">Strona główna </a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'boxes:user_profile' %}"> Mój profil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'boxes:losuj' %}"> Losuj</a>
            </li>
        {% endif %}
    </ul>
{% endblock navbar %}


{% block content %}

    <div class="container">
        {% if not user.is_authenticated %}
            <h2> Zaloguj się, zanim zaczniesz korzystać ze strony!</h2>
        {% else %}


            <div class="jumbotron media border">

                <div class="media-body">

                    <div class="card" style="width:400px">
                        <div class="card-body">
                            <h4 class="card-title">
                                {% if user.is_authenticated %}
                                    <h2> Witamy {{ user.username }}!</h2>
                                {% endif %}
                            </h4>
                            <div class="card-text">
                                <ul>
                                    <p> Nazwisko: {{ person.second_name }} </p>
                                    <p> Imię: {{ person.first_name }} </p>
                                    {% if user.chosen_person %}
                                        <p class="badge badge-pill badge-success"> Już wylosowano! </p>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>

                    </div>

                </div>

                {% if person.is_man %}
                    {% load static %}
                    <img src="{% static 'avatar_m.png' %}" alt="John Doe"
                         class="ml-3 mt-3 rounded-circle card-img-bottom"
                         style="width: 200px;">
                {% else %}
                    {% load static %}
                    <img src="{% static 'avatar_f.png' %}" alt="John Doe"
                         class="ml-3 mt-3 rounded-circle card-img-bottom"
                         style="width: 200px;">
                {% endif %}
            </div>

            <div class="jumbotron">
                Powyżej możesz sprawdzić, czy zalogowałeś się jako poprawny użytkownik. Jeśli to nie Ty, lepiej się
                wyloguj...
                <p></p>
                <b>Twórcy tej aplikacji zapewniają, że wyniki losowania są całkowicie tajne i nikt z nich nie będzie
                    starał się ich sprawdzać w sposób pozwalający na ustalenie, kto kogo wylosował.</b> <br>
                <p></p>
                Losowanie odbywać się będzie w następujący sposób:

                <ol>
                    <li>Uczestnicy logują się i sprawdzają poprawność kont.</li>
                    <li>W panelu "Losuj" wszyscy wylosują swoją karteczkę.</li>
                    <li>W tym samym panelu będzie możliwość sprawdzenia, kto został wylosowany.</li>
                    <li>Jeśli losowanie z jakiegoś powodu nie powiedzie się, zostanie wyświetlony stosowny komunikat.
                    </li>
                    <li>W przypadku błędu - losowanie zostanie powtórzone
                        <b>od początku</b>.
                    </li>
                    <li>Jeżeli liczba takich powtórzeń przekroczy poziom cierpliwości uczestników losowania,
                        zostanie wykorzystana opcja awaryjna, polegająca na odgórnym całkowicie automatycznym losowaniu.
                    </li>
                </ol>

            </div>
        {% endif %}
    </div>

{% endblock content %}